# Generated by Django 4.2 on 2024-02-20 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='profiles.profile'),
        ),
    ]
